export default {
  FrameType: {
    ARNETWORKAL_FRAME_TYPE_UNINITIALIZED: 0,
    ARNETWORKAL_FRAME_TYPE_ACK: 1,
    ARNETWORKAL_FRAME_TYPE_DATA: 2,
    ARNETWORKAL_FRAME_TYPE_DATA_LOW_LATENCY: 3,
    ARNETWORKAL_FRAME_TYPE_DATA_WITH_ACK: 4,
    ARNETWORKAL_FRAME_TYPE_MAX: 5
  },
  FrameId: {
    BD_NET_CD_NONACK_ID: 10,
    BD_NET_CD_ACK_ID: 11,
    BD_NET_CD_EMERGENCY_ID: 12,
    BD_NET_CD_VIDEO_ACK_ID: 13,
    BD_NET_DC_VIDEO_DATA_ID: 125,
    BD_NET_DC_EVENT_ID: 126,
    BD_NET_DC_NAVDATA_ID: 127
  },
  BufferId: {
    ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PING: 0,
    ARNETWORK_MANAGER_INTERNAL_BUFFER_ID_PONG: 1
  },
  ProjectId: {
    ARCOMMANDS_ID_PROJECT_COMMON: 0,
    ARCOMMANDS_ID_PROJECT_ARDRONE3: 1
  },
  ClassId: {
    ARCOMMANDS_ID_COMMON_CLASS_COMMON: 4,
    ARCOMMANDS_ID_ARDRONE3_CLASS_PILOTING: 0,
    ARCOMMANDS_ID_ARDRONE3_CLASS_MEDIASTREAMING: 21
  },
  CmdId: {
    ARCOMMANDS_ID_COMMON_COMMON_CMD_ALLSTATES: 0,
    ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_FLATTRIM: 0,
    ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_TAKEOFF: 1,
    ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_PCMD: 2,
    ARCOMMANDS_ID_ARDRONE3_PILOTING_CMD_LANDING: 3,
    ARCOMMANDS_ID_ARDRONE3_MEDIASTREAMING_CMD_VIDEOENABLE: 0,
    ARCOMMANDS_ID_ARDRONE3_MEDIASTREAMING_CMD_VIDEOSTREAMMODE: 1
  }
};
